AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    temp_asess_Rep

    Sample SAM Template for temp_asess_Rep

Parameters:
    EnvName:
        Description: 'The environment name for the stack'
        Type: String
        Default: dev
    SupabaseUrl:
        Description: 'Supabase url for client connection'
        Type: String
    SupabaseKey:
        Description: 'Supabase key for client connection'
        Type: String

Globals:
    Function:
        Timeout: 3
        LoggingConfig:
            LogFormat: JSON

Resources:
    SupabaseSetupFn:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: app.lambdaHandler
            Runtime: nodejs20.x
            Environment:
                Variables:
                    SUPABASE_URL: !Ref SupabaseUrl
                    SUPABASE_KEY: !Ref SupabaseKey
            Architectures:
                - x86_64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /supabase
                        Method: get
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                EntryPoints:
                    - src/lambdas/SupabaseSetup/app.ts
                Bundle: true
                Minify: true
                Sourcemap: true
                Target: es2022
                Format: esm
                OutExtension:
                    - .js=.mjs
